dist: bionic
addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
language: node_js
node_js:
    - lts/*
script:
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
