language: node_js

node_js:
  - lts/*

os: linux
dist: bionic

addons:
  chrome: stable

services:
  - mongodb

install:
  - npm install
  - npm install cors
  - npm install github:kkrings/weltenbummlerpaar-backend

before_script:
  - node node_modules/weltenbummlerpaar-backend/bin/create.js admin --username admin --password admin
  - node_modules/pm2/bin/pm2 start e2e/backend.config.js

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

after_script:
  - node_modules/pm2/bin/pm2 stop weltenbummlerpaar-backend
  - node_modules/pm2/bin/pm2 delete weltenbummlerpaar-backend
